// Cached list of popular Google Fonts for the brand kit font pickers. This is
// a static list on purpose (the brief calls for no live Google Fonts API call).
// Keep it alphabetized so the searchable dropdowns scan predictably.
// Add more as needed.
export const GOOGLE_FONTS: string[] = [
  "Abril Fatface",
  "Albert Sans",
  "Alegreya",
  "Alegreya Sans",
  "Anton",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Arvo",
  "Asap",
  "Assistant",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Be Vietnam Pro",
  "Bebas Neue",
  "Bitter",
  "Bodoni Moda",
  "Bricolage Grotesque",
  "Cabin",
  "Cardo",
  "Catamaran",
  "Caveat",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Cormorant",
  "Cormorant Garamond",
  "Crimson Pro",
  "Crimson Text",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dancing Script",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Exo 2",
  "Figtree",
  "Fira Sans",
  "Frank Ruhl Libre",
  "Fraunces",
  "Geologica",
  "Gloock",
  "Great Vibes",
  "Hanken Grotesk",
  "Heebo",
  "Hind",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inria Sans",
  "Instrument Sans",
  "Instrument Serif",
  "Inter",
  "Inter Tight",
  "Josefin Sans",
  "Jost",
  "Kanit",
  "Karla",
  "Lato",
  "Lexend",
  "Libre Baskerville",
  "Libre Caslon Text",
  "Libre Franklin",
  "Literata",
  "Lobster",
  "Lora",
  "Manrope",
  "Marcellus",
  "Maven Pro",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Mulish",
  "Newsreader",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Onest",
  "Open Sans",
  "Oswald",
  "Outfit",
  "Overpass",
  "PT Sans",
  "PT Serif",
  "Pacifico",
  "Passion One",
  "Petrona",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prata",
  "Prompt",
  "Public Sans",
  "Questrial",
  "Quicksand",
  "Raleway",
  "Red Hat Display",
  "Red Hat Text",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Rubik",
  "Rufina",
  "Sacramento",
  "Sarabun",
  "Satisfy",
  "Schibsted Grotesk",
  "Signika",
  "Sora",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Spectral",
  "Staatliches",
  "Syne",
  "Tajawal",
  "Titillium Web",
  "Ubuntu",
  "Unbounded",
  "Unna",
  "Urbanist",
  "Varela Round",
  "Vollkorn",
  "Work Sans",
  "Yeseva One",
  "Zilla Slab",
];
