// Cached list of popular Google Fonts for the brand kit font pickers. This is
// a static list on purpose (the brief calls for no live Google Fonts API call).
// Keep it alphabetized so the searchable dropdowns scan predictably.
// Add more as needed.
export const GOOGLE_FONTS: string[] = [
  "Abril Fatface",
  "Advent Pro",
  "Alata",
  "Albert Sans",
  "Alegreya",
  "Alegreya Sans",
  "Alice",
  "Amatic SC",
  "Anton",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Arimo",
  "Arvo",
  "Asap",
  "Assistant",
  "Baloo 2",
  "Bangers",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Be Vietnam Pro",
  "Bebas Neue",
  "Besley",
  "Bitter",
  "Bodoni Moda",
  "Bree Serif",
  "Bricolage Grotesque",
  "Cabin",
  "Cairo",
  "Cardo",
  "Castoro",
  "Catamaran",
  "Caveat",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Cormorant",
  "Cormorant Garamond",
  "Courgette",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dancing Script",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Eczar",
  "Encode Sans",
  "Epilogue",
  "Exo 2",
  "Faustina",
  "Figtree",
  "Fira Code",
  "Fira Sans",
  "Fjalla One",
  "Frank Ruhl Libre",
  "Fraunces",
  "Gelasio",
  "Geologica",
  "Gloock",
  "Gothic A1",
  "Great Vibes",
  "Halant",
  "Handlee",
  "Hanken Grotesk",
  "Heebo",
  "Hepta Slab",
  "Hind",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Inria Sans",
  "Instrument Sans",
  "Instrument Serif",
  "Inter",
  "Inter Tight",
  "Italiana",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "Kalam",
  "Kanit",
  "Karla",
  "Kumbh Sans",
  "Lato",
  "League Spartan",
  "Lexend",
  "Libre Baskerville",
  "Libre Caslon Text",
  "Libre Franklin",
  "Lilita One",
  "Literata",
  "Lobster",
  "Lora",
  "Lustria",
  "Manrope",
  "Marcellus",
  "Marcellus SC",
  "Maven Pro",
  "Merienda",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Mukta",
  "Mulish",
  "Neuton",
  "Newsreader",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Old Standard TT",
  "Onest",
  "Open Sans",
  "Oswald",
  "Outfit",
  "Overpass",
  "Oxygen",
  "PT Sans",
  "PT Serif",
  "Pacifico",
  "Passion One",
  "Petrona",
  "Philosopher",
  "Play",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prata",
  "Prompt",
  "Public Sans",
  "Quattrocento",
  "Questrial",
  "Quicksand",
  "Raleway",
  "Rasa",
  "Recursive",
  "Red Hat Display",
  "Red Hat Text",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Rokkitt",
  "Rubik",
  "Rufina",
  "Sacramento",
  "Sarabun",
  "Satisfy",
  "Schibsted Grotesk",
  "Sen",
  "Shadows Into Light",
  "Signika",
  "Six Caps",
  "Sora",
  "Sorts Mill Goudy",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Spectral",
  "Staatliches",
  "Syne",
  "Tajawal",
  "Tinos",
  "Titillium Web",
  "Trirong",
  "Ubuntu",
  "Unbounded",
  "Unna",
  "Urbanist",
  "Varela Round",
  "Vollkorn",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yeseva One",
  "Zilla Slab",
];
