// Cached list of popular Google Fonts for the brand kit font dropdowns. This is
// a static list on purpose (the brief calls for no live Google Fonts API call).
// Add more as needed.
export const GOOGLE_FONTS: string[] = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "Work Sans",
  "Source Sans 3",
  "Source Serif 4",
  "Merriweather",
  "Playfair Display",
  "Lora",
  "PT Serif",
  "PT Sans",
  "Rubik",
  "Mulish",
  "Karla",
  "DM Sans",
  "DM Serif Display",
  "Manrope",
  "Figtree",
  "Outfit",
  "Plus Jakarta Sans",
  "Libre Franklin",
  "Libre Baskerville",
  "Cormorant Garamond",
  "EB Garamond",
  "Crimson Text",
  "Josefin Sans",
  "Quicksand",
  "Oswald",
  "Bebas Neue",
  "Archivo",
  "Space Grotesk",
  "Fraunces",
  "Bitter",
  "Cabin",
];
